version: '3.2'
services:
  node:
    build: .
    volumes:
      - ./:/usr/src/app
      - node_modules:/usr/src/node_modules
    ports:
      - "8082:8080"
    restart: unless-stopped
volumes:
  node_modules:
